name = "smaregi-mcp"
main = "dist/worker/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 対象となるワーカーのタイプ
workers_dev = true

# カスタムドメイン設定（オプション）
# route = "smaregi-mcp.example.com/*"

# KVネームスペースの設定
[[kv_namespaces]]
binding = "SESSIONS"
id = "211b932e0cc24c66b86c109ad8919aa3"

[[kv_namespaces]]
binding = "TOKENS"
id = "d32b32df7285453193aacd29f84a262f"

# D1データベースの設定（将来の拡張用）
# [[d1_databases]]
# binding = "DB"
# database_name = "smaregi-mcp-cache"
# database_id = "YOUR_D1_DATABASE_ID"

# 各環境の設定
[env.production]
# 本番環境用の設定
# 実際のIDは管理画面から取得した値で置き換える
kv_namespaces = [
  { binding = "SESSIONS", id = "PRODUCTION_SESSIONS_ID" },
  { binding = "TOKENS", id = "PRODUCTION_TOKENS_ID" }
]
# シークレットはワーカー管理画面やCLIから設定する
# wrangler secret put CLIENT_ID
# wrangler secret put CLIENT_SECRET

[env.staging]
# ステージング環境用の設定
kv_namespaces = [
  { binding = "SESSIONS", id = "STAGING_SESSIONS_ID" },
  { binding = "TOKENS", id = "STAGING_TOKENS_ID" }
]

# ビルド設定
[build]
command = "npm run build:cloudflare"

# ローカル開発設定
[dev]
port = 8787
local_protocol = "http"

# ワーカーの設定変数
[vars]
DEBUG = "false"
SERVER_NAME = "smaregi"
SERVER_VERSION = "1.0.0"
# リダイレクトURIは実際のWorkers URLに置き換えてください
REDIRECT_URI = "https://smaregi-mcp.youraccount.workers.dev/auth/callback"
SMAREGI_AUTH_URL = "https://id.smaregi.dev/authorize"
SMAREGI_TOKEN_ENDPOINT = "https://id.smaregi.dev/authorize/token"
SMAREGI_API_URL = "https://api.smaregi.dev"
NODE_ENV = "production"

# MCP関連の設定
MCP_TRANSPORT = "sse"
MCP_BASE_URL = "https://smaregi-mcp.youraccount.workers.dev"

# 定期実行設定（必要に応じて）
# [triggers]
# crons = ["0 0 * * *"] # 毎日午前0時に実行