parameters:
  - name: id
    in: path
    description: 商品ID
    required: true
    schema:
      type: integer
      format: int64
  - name: reservation_product_id
    in: path
    description: 引当商品ID
    required: true
    schema:
      type: integer
      format: int64

get:
  summary: 特定の商品在庫引当情報取得
  description: 指定した商品IDと引当商品IDの在庫引当情報を取得します。
  operationId: getProductInventoryReservation
  tags:
    - 商品
  parameters:
    - name: fields
      in: query
      description: 取得するフィールド
      schema:
        type: array
        items:
          type: string
        default: ["*"]
  responses:
    '200':
      description: 商品の在庫引当情報を返却
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductInventoryReservation'
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 商品または在庫引当情報が存在しない
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:read
    - UserAccessToken:
        - pos.products:read

put:
  summary: 商品の在庫引当情報更新
  description: 指定した商品IDと引当商品IDの在庫引当情報を更新します。
  operationId: updateProductInventoryReservation
  tags:
    - 商品
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/ProductInventoryReservation'
  responses:
    '200':
      description: 商品の在庫引当情報の更新に成功
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductInventoryReservation'
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 商品または在庫引当情報が存在しない
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '409':
      description: 既存データとの競合エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:write
    - UserAccessToken:
        - pos.products:write

delete:
  summary: 商品の在庫引当情報削除
  description: 指定した商品IDと引当商品IDの在庫引当情報を削除します。
  operationId: deleteProductInventoryReservation
  tags:
    - 商品
  responses:
    '204':
      description: 商品の在庫引当情報の削除に成功
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 商品または在庫引当情報が存在しない
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '409':
      description: 削除できない状態（他のデータから参照されているなど）
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:write
    - UserAccessToken:
        - pos.products:write
