parameters:
  - name: id
    in: path
    description: 商品ID
    required: true
    schema:
      type: integer
      format: int64

get:
  summary: 商品の価格変更履歴取得
  description: 指定した商品IDの価格変更履歴を取得します。
  operationId: getProductPriceChanges
  tags:
    - 商品
  parameters:
    - name: storeId
      in: query
      description: 店舗ID
      schema:
        type: integer
        format: int64
    - name: priceDivision
      in: query
      description: 価格区分
      schema:
        type: integer
        format: int32
    - name: limit
      in: query
      description: 取得件数
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 1000
        default: 100
    - name: page
      in: query
      description: ページ番号
      schema:
        type: integer
        format: int32
        minimum: 1
        default: 1
    - name: fields
      in: query
      description: 取得するフィールド
      schema:
        type: array
        items:
          type: string
        default: ["*"]
  responses:
    '200':
      description: 商品価格変更履歴を返却
      content:
        application/json:
          schema:
            type: object
            properties:
              items:
                type: array
                items:
                  $ref: '#/components/schemas/ProductPriceChange'
              total:
                type: integer
                description: 総件数
              limit:
                type: integer
                description: 取得件数
              page:
                type: integer
                description: ページ番号
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '404':
      description: 商品が存在しない
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  security:
    - AppAccessToken:
        - pos.products:read
    - UserAccessToken:
        - pos.products:read
