name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers Production
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build:cloudflare
        
      - name: Deploy to Production
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --env production
          
      - name: Create deployment notification
        uses: actions/github-script@v7
        if: success()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const accountId = '${{ secrets.CLOUDFLARE_ACCOUNT_ID }}';
            const workerName = 'smaregi-mcp';
            const productionUrl = `https://${workerName}.${accountId}.workers.dev`;
            
            // Get the commit message
            const commit = context.payload.head_commit;
            const commitMessage = commit.message;
            const commitUrl = commit.url;
            const author = commit.author.name;
            
            console.log(`✅ Production deployment successful!
            
            URL: ${productionUrl}
            Commit: ${commitMessage}
            Author: ${author}
            Link: ${commitUrl}`);
            
      - name: Notify deployment failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            core.setFailed('Production deployment failed. Please check the logs.');